feat: Rust implementation for some Cairo types
eigerco/axelar-amplifier pull request #18
Opened 2024-04-24 15:36 UTC by ctoyan

## Description

Implements [#77](https://github.com/eigerco/giza-axelar-starknet/issues/77) in the `giza-axelar-starknet` repository.
Adds Rust representations for some Cairo types.

## Todos

- [x] Unit tests
- [x] Manual tests
- [x] Documentation
- [x] Connect epics/issues

## Steps to Test
Run the unit tests.

2024-04-25 10:37 UTC, tomekpiotrowski requested changes

2024-04-25 10:37 UTC, tomekpiotrowski commented on ampd/src/starknet/types/array_span.rs
> +/// ## Example usage with the strging "hello"
typo

2024-04-25 10:37 UTC, tomekpiotrowski commented on ampd/src/starknet/types/array_span.rs
> +mod array_span_tests {
:+1:

2024-04-25 10:37 UTC, tomekpiotrowski commented on ampd/src/starknet/types/byte_array.rs
> +/// ## Example usage with the strging "hello"
same typo

2024-04-29 11:40 UTC, tomekpiotrowski approved these changes

2024-04-29 16:19 UTC, ctoyan commented
Test pass and clippy passes locally.
I presume that the CI doesn't pass, because Axelar use a custom workflow runner and in our organisation the tasks just stay queued and are never picked up.

2024-04-29 16:20 UTC, merged